/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    Login: typeof import('./components/Login.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MenuAdmin: typeof import('./components/MenuAdmin.vue')['default']
    MenuComponent: typeof import('./components/MenuComponent.vue')['default']
    MenuUser: typeof import('./components/MenuUser.vue')['default']
    OrderDetail: typeof import('./components/OrderDetail.vue')['default']
    OrderForm: typeof import('./components/OrderForm.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouteDetailForm: typeof import('./components/RouteDetailForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTicketForm: typeof import('./components/SearchTicketForm.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    TrainDescription: typeof import('./components/TrainDescription.vue')['default']
    TrainDetail: typeof import('./components/TrainDetail.vue')['default']
    TrainManageDetail: typeof import('./components/TrainManageDetail.vue')['default']
    TrainManageForm: typeof import('./components/TrainManageForm.vue')['default']
    UserInfoComponent: typeof import('./components/UserInfoComponent.vue')['default']
    UserOrders: typeof import('./components/UserOrders.vue')['default']
  }
}
